name: Lint

on:
  workflow_call:

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.13

      - name: Install dependencies
        run: uv sync --frozen --group dev

      - name: Ruff format
        run: uv run ruff format . --check

      - name: Ruff check
        run: uv run ruff check .
