name: Linting

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main
      - next

env:
  DEFAULT_PYTHON: "3.14.2"

permissions:
  pull-requests: write
  statuses: write

jobs:
  validate-pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            docs
            refactor
            chore
            fix
            feat
            breaking
          scopes: |
            ci
            core
          requireScope: true
          ignoreLabels: |
            bot
          subjectPattern: ^.+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          wip: true
  pre-commit:
    runs-on: "ubuntu-latest"
    name: Pre-commit
    steps:
      - name: Check out the repository
        uses: actions/checkout@v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        run: uv python install ${{ env.DEFAULT_PYTHON }}

      - name: Install dev dependencies
        run: uv sync --frozen --group dev

      - name: Run pre-commit on all files
        run: uv run pre-commit run --all-files --show-diff-on-failure --color=always
  hacs:
    runs-on: "ubuntu-latest"
    name: HACS Validation
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v6.0.2"

      - name: HACS validation
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"

  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Setup Python ${{ env.DEFAULT_PYTHON }}
        run: uv python install ${{ env.DEFAULT_PYTHON }}

      - name: Install requirements
        run: uv sync --frozen --group dev

      - name: Unit tests suite
        run: |
          uv run pytest \
            --timeout=9 \
            --durations=10 \
            --cov-fail-under=40 \
            --junitxml=pytest.xml \
            --cov-report=term-missing:skip-covered \
            tests/ | tee pytest-coverage.txt
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
